/**
 * Token loader   " Plan 06   3.1 step 3 (narrowed).
 *
 * Platform tokens (--bs-*, Forma shared/light/dark) are now delivered
 * statically via tokens.css (generated by scripts/generate-tokens-css.mjs,
 * imported before global.css in main.tsx). The cascade and HMR work without
 * this function for platform tokens.
 *
 * applyTokens() now has TWO responsibilities only:
 *   1. Flip data-theme on <html> so [data-theme='light'] overrides activate.
 *   2. Write user-defined project tokens (FR-191 design-token editing)   "
 *      caller passes a flat Record<string, string> of --custom-prop: value pairs.
 *
 * It must NEVER re-inject platform tokens (those live in tokens.css, SSOT).
 *
 * VALUE-FREE BY CONTRACT (Plan 06   3.1, RC-1/RC-2): no literal values here.
 * Governed by: Doc 05   10, FR-191, IL-13.
 */
import tokens from './tokens.json';

export function applyTokens(
  theme: 'dark' | 'light' = 'dark',
  root: HTMLElement = typeof document !== 'undefined' ? document.documentElement : (null as unknown as HTMLElement),
  /** FR-191: user-defined project tokens to inject (optional). */
  projectTokens?: Record<string, string>,
): void {
  if (!root) return;
  // 1. Theme switch   " activates [data-theme='light'] block in tokens.css.
  root.setAttribute('data-theme', theme);
  // 2. Project tokens only (FR-191). Platform tokens are static in tokens.css.
  if (projectTokens) {
    for (const [name, value] of Object.entries(projectTokens)) {
      root.style.setProperty(name, value);
    }
  }
}

/** Count of nodes affected by a token edit   " FR-191 affected-node preview hook. */
function tokenVarName(path: string): string {
  return `--bs-${path.replace(/\./g, '-')}`;
}

;
