/**
 * Icon registry (Phase 2.9   " audit U-1  * UI Kit Phase 1   " plan   3.2/  5).
 * The single source of icon glyphs for toolbars, cards, trees and row actions.
 *
 * Internals are re-exported from `lucide-react` (pinned exact version) at the
 * reference standard: 1.75px stroke, 24px grid, `currentColor` (design-system
 * ref   04). The public API is unchanged   " `Icons.<name>` returns a ReactNode
 * and `IconName` is the key union   " so zero call-site logic changes.
 * Sizing stays in CSS (context rules like `.uk-iconbtn svg { width/height }`).
 */
import type { ReactNode } from 'react';
import {
  AlertCircle,
  AlertTriangle,
  AlignCenterHorizontal,
  Braces,
  AlignCenterVertical,
  AlignEndHorizontal,
  AlignEndVertical,
  AlignHorizontalDistributeCenter,
  AlignStartHorizontal,
  AlignStartVertical,
  AlignVerticalDistributeCenter,
  Box,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleDot,
  Clapperboard,
  Clock,
  Code,
  Component,
  Copy,
  Diamond,
  DiamondPlus,
  Eye,
  EyeOff,
  Flag,
  Folder,
  Frame,
  Globe,
  Grid2x2,
  GripVertical,
  Group,
  Heading,
  Image,
  Layers,
  LayoutGrid,
  LayoutPanelTop,
  LayoutTemplate,
  Link,
  Lock,
  LockOpen,
  MapPin,
  Maximize,
  Minus,
  MousePointer2,
  Move,
  Music,
  Navigation,
  Palette,
  PanelBottom,
  Pause,
  Pencil,
  Play,
  Plus,
  RectangleHorizontal,
  RefreshCw,
  Repeat,
  Rotate3d,
  Scaling,
  Search,
  Shapes,
  SkipBack,
  SkipForward,
  Sparkles,
  Square,
  Star,
  Sun,
  Moon,
  Tag,
  Trash2,
  TrendingUp,
  Type,
  Undo2,
  Redo2,
  Upload,
  Video,
  X,
  Settings,
  Monitor,
  Tablet,
  Smartphone,
  HelpCircle,
  type LucideIcon,
} from 'lucide-react';

/** Reference   04 contract: single 1.75px line weight on the 24px grid. */
const STROKE = 1.75;

function icon(Cmp: LucideIcon): ReactNode {
  return <Cmp strokeWidth={STROKE} aria-hidden="true" focusable="false" />;
}

export const Icons = {
  /* transform tools (Doc 05   5) */
  select: icon(MousePointer2),
  move: icon(Move),
  rotate: icon(Rotate3d),
  scale: icon(Scaling),
  world: icon(Globe),
  local: icon(MapPin),
  frame: icon(Frame),
  /* row / card actions */
  duplicate: icon(Copy),
  trash: icon(Trash2),
  replace: icon(RefreshCw),
  rename: icon(Pencil),
  plus: icon(Plus),
  minus: icon(Minus),
  drag: icon(GripVertical),
  star: icon(Star),
  starFilled: <Star strokeWidth={STROKE} fill="currentColor" aria-hidden="true" focusable="false" />,
  folder: icon(Folder),
  tag: icon(Tag),
  search: icon(Search),
  eye: icon(Eye),
  eyeOff: icon(EyeOff),
  lock: icon(Lock),
  unlock: icon(LockOpen),
  undo: icon(Undo2),
  redo: icon(Redo2),
  maximize: icon(Maximize),
  /* timeline / transport */
  marker: icon(Flag),
  loop: icon(Repeat),
  play: icon(Play),
  pause: icon(Pause),
  skipBack: icon(SkipBack),
  skipForward: icon(SkipForward),
  diamond: icon(Diamond),
  diamondPlus: icon(DiamondPlus),
  track: icon(TrendingUp),
  clock: icon(Clock),
  /* scene nodes (Doc 05   5) */
  camera: icon(Video),
  light: icon(Sun),
  cube: icon(Box),
  sphere: icon(Circle),
  group: icon(Group),
  anchor: icon(CircleDot),
  /* DOM elements (FR-120) */
  section: icon(LayoutPanelTop),
  container: icon(Square),
  heading: icon(Heading),
  text: icon(Type),
  buttonEl: icon(RectangleHorizontal),
  image: icon(Image),
  audio: icon(Music),
  video: icon(Clapperboard),
  link: icon(Link),
  navigation: icon(Navigation),
  footer: icon(PanelBottom),
  shapes: icon(Shapes),
  sparkles: icon(Sparkles),
  flex: icon(LayoutTemplate),
  grid: icon(Grid2x2),
  braces: icon(Braces),
  component: icon(Component),
  code: icon(Code),
  layers: icon(Layers),
  layoutGrid: icon(LayoutGrid),
  palette: icon(Palette),
  /* align / distribute (01 SelectionSystem toolbar) */
  alignLeft: icon(AlignStartVertical),
  alignCenterH: icon(AlignCenterVertical),
  alignRight: icon(AlignEndVertical),
  alignTop: icon(AlignStartHorizontal),
  alignCenterV: icon(AlignCenterHorizontal),
  alignBottom: icon(AlignEndHorizontal),
  distributeH: icon(AlignHorizontalDistributeCenter),
  distributeV: icon(AlignVerticalDistributeCenter),
  warning: icon(AlertTriangle),
  error: icon(AlertCircle),
  check: icon(Check),
  chevronDown: icon(ChevronDown),
  chevronRight: icon(ChevronRight),
  close: icon(X),
  publish: icon(Upload),
  settings: icon(Settings),
  /* device profiles */
  desktop: icon(Monitor),
  tablet: icon(Tablet),
  mobile: icon(Smartphone),
  smartphone: icon(Smartphone),
  sun: icon(Sun),
  moon: icon(Moon),
  help: icon(HelpCircle),
} as const;

type IconName = keyof typeof Icons;
